# Generated by Django 5.1.2 on 2024-12-12 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0006_estudiante_tarifa_personalizada'),
        ('facturaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptofactura',
            name='es_pago_adelantado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada Parcialmente', 'Pagada Parcialmente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoAdelantado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_pago', models.CharField(choices=[('50%', '50% del año escolar'), ('100%', '100% del año escolar')], default='50%', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_adelantados', to='estudiante.estudiante')),
            ],
        ),
    ]
