# Generated by Django 5.1.2 on 2024-12-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturaciones', '0002_conceptofactura_es_pago_adelantado_factura_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptofactura',
            name='es_anio_escolar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptofactura',
            name='es_inscripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptofactura',
            name='es_mensualidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='mes',
            field=models.CharField(choices=[('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre'), ('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Transferencia Bancaria', 'Transferencia Bancaria'), ('Efectivo', 'Efectivo'), ('Cheque', 'Cheque'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
    ]
