# Generated by Django 5.1.2 on 2024-12-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_alter_estudiante_seccion'),
        ('grado', '0002_alter_grado_nombre'),
        ('seccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seccion',
            new_name='Secciones',
        ),
    ]
