# Generated by Django 5.1.2 on 2024-11-19 21:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Aplleidos')),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(choices=[('A', 'Azua'), ('BH', 'Bahoruco'), ('BA', 'Barahona'), ('D', 'Dajabón'), ('DN', 'Distrito Nacional'), ('DU', 'Duarte'), ('EP', 'Elías Piña'), ('ES', 'El Seibo'), ('E', 'Espaillat'), ('H', 'Hato Mayor'), ('HM', 'Hermanas Mirabal'), ('I', 'Independencia'), ('LA', 'La Altagracia'), ('LR', 'La Romana'), ('LV', 'La Vega'), ('MTS', 'María Trinidad Sánchez'), ('MN', 'Monseñor Nouel'), ('MC', 'Monte Cristi'), ('MT', 'Monte Plata'), ('P', 'Pedernales'), ('PR', 'Peravia'), ('PP', 'Puerto Plata'), ('S', 'Samaná'), ('SR', 'Sánchez Ramírez'), ('SC', 'San Cristóbal'), ('SJO', 'San José de Ocoa'), ('SJ', 'San Juan'), ('SPM', 'San Pedro de Macorís'), ('SA', 'Santiago'), ('SAR', 'Santiago Rodríguez'), ('SD', 'Santo Domingo'), ('V', 'Valverde')], max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('anio_escolar', models.CharField(max_length=10)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='seccion.seccion')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
