# Generated by Django 5.1.2 on 2024-12-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_estudiante_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='promedio',
        ),
    ]
