# Generated by Django 5.1.2 on 2024-12-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
