# Generated by Django 5.1.2 on 2024-11-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grado', '__first__'),
        ('profesor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='grado.grado')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='profesor.profesor')),
            ],
        ),
    ]
