# Generated by Django 5.1.2 on 2024-11-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='aula.aula')),
            ],
        ),
    ]
