# Generated by Django 5.1.2 on 2024-12-12 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0001_initial'),
        ('calificaion', '0001_initial'),
        ('estudiante', '0006_estudiante_tarifa_personalizada'),
        ('grado', '0002_alter_grado_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='grado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='grado.grado'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('estudiante', 'asignatura', 'grado')},
        ),
    ]
