# Generated by Django 5.1.2 on 2024-12-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaion', '0003_alter_calificacion_grado'),
        ('grado', '0002_alter_grado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='grado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='grado.grado'),
        ),
    ]
