# Generated by Django 5.1.2 on 2024-12-12 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grado', '0002_alter_grado_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa_escolar', to='grado.grado')),
            ],
        ),
    ]
